### ISSUE TITLE
Error in register View

### ISSUE THREAD

**Issue by avp90** [HTML24/FoosLeader#4]
Hi, i would try the FoosLeader App.
Can you update your packages, i get this Error on localhost:8000/register:
https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1775

**Comment by tomgud** [comment]
Have you tried running the command `composer install`? Can't really duplicate your error.

**Comment by avp90** [comment]
Yes, i tried `composer install` and `composer update`.

**Comment by tomgud** [comment]
Hey, sorry for the late reply. 

Just got it installed locally and recreated the error, hopefully will find a fix soon.

**Comment by tomgud** [comment]
@adrianpop1990 Can you try again?

**Comment by tomgud** [comment]
Closing this issue since it should be resolved now - please create a new one if this problem persists, or another one has emerged.
